version: "3.8"

services:
  countshare:
    image: ghcr.io/wallechfox/countshare:latest
    container_name: countshare
    ports:
      - "8000:8000"
    volumes:
      - /www/countshare/files:/files
      - countshare-data:/data
    environment:
      - ADMIN_PATH=my-secret-admin
    restart: unless-stopped

volumes:
  countshare-data:
